# Generated by Django 6.0.4 on 2026-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date time')),
                ('flux', models.FloatField(default=0.0)),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
