# Generated by Django 6.0.4 on 2026-04-28 19:24

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('age', models.IntegerField(default=18)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
